version: "3.5"

networks:
  devnet:
    name: ${NETWORK_NAME:?err}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 7.0.0.0/24

services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.nimiq.address=:8443
      - --entrypoints.rpc.address=:8648
      - --providers.docker=true
    ports:
      - "8443:8443"
      - "8648:8648"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      devnet:
        ipv4_address: 7.0.0.100

  seed1:
    image: nimiq-albatross:latest
    build:
      context: albatross
      dockerfile: build_ubuntu.Dockerfile
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed1.rule=Host(`seed1.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed1.entrypoints=nimiq
      - traefik.http.routers.seed1.service=seed1
      - traefik.http.services.seed1.loadbalancer.server.port=8443

      # Accept outside RPC connections
      - traefik.http.routers.seed1-rpc.rule=Host(`seed1.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed1-rpc.entrypoints=rpc
      - traefik.http.routers.seed1-rpc.service=seed1-rpc
      - traefik.http.services.seed1-rpc.loadbalancer.server.port=8648
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.2/tcp/8443/ws
      - NIMIQ_HOST=seed1.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ20TSB0DFSMUH9C15GQGAGJTTE4D3MA859E
      - SIGNING_KEY=041580cc67e66e9e08b68fd9e4c9deb68737168fbe7488de2638c2e906c2f5ad
      - VOTING_KEY=ac29bc07201d3d09f34078b44abd060a5399654db8d2da9876716082b5d329e7c54cc9668994461ef20bd7f5fdc3033ceb22bc9e052c287aa3a476814608ab995c88b02037e2bc5de7896d645294b2645aa8697cb51b24ed40a2d2726df300
      - FEE_KEY=6c9320ac201caf1f8eaa5b05f5d67a9e77826f3f6be266a0ecccc20416dc6587
      - RPC_ENABLED=true
      # - RPC_USERNAME=rpcclient
      # - RPC_PASSWORD=7F8E0E42-8ACF-47E7-8CC1-0EC66FA3D82D
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.2
    # volumes:
    #   - "seed1:/home/nimiq/.nimiq:rw"

  seed2:
    image: nimiq-albatross:latest
    build:
      context: albatross
      dockerfile: build_ubuntu.Dockerfile
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed2.rule=Host(`seed2.${NETWORK_NAME:?err}`)
      # Accept outside RPC connections
      - traefik.http.routers.seed2-rpc.rule=Host(`seed2.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed2-rpc.entrypoints=rpc
      - traefik.http.routers.seed2-rpc.service=seed2-rpc
      - traefik.http.services.seed2-rpc.loadbalancer.server.port=8648
    depends_on:
      - seed1
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.3/tcp/8443/ws
      - NIMIQ_HOST=seed2.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ69MH903M5HDFNU8E8453FXJSY6XYQSN2CE
      - SIGNING_KEY=aed203193d0464f2a584087dd0bd17cca83b831cfd967c238a464a5b9dc30db7
      - VOTING_KEY=66846a7a3dbf54847d87393c08e06deb3017a523fdad2ace7c2b259010517372e076d610d109c5854bfcf11b9c77450b9fd777ed156be29c8877df520b4bd7b25534a21023b57b285596ddf233ead763a7cd1d0c5db9f1b22662befe49b900
      - FEE_KEY=6648bedb41bd47e68218e0b0b939e700d42c4f3cb4c70abaa1b76a7ca880d81b
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.3
    # volumes:
    #   - "seed2:/home/nimiq/.nimiq:rw"

  seed3:
    image: nimiq-albatross:latest
    build:
      context: albatross
      dockerfile: build_ubuntu.Dockerfile
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed3.rule=Host(`seed3.${NETWORK_NAME:?err}`)
      # Accept outside RPC connections
      - traefik.http.routers.seed3-rpc.rule=Host(`seed3.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed3rpc.entrypoints=rpc
      - traefik.http.routers.seed3-rpc.service=seed3-rpc
      - traefik.http.services.seed3-rpc.loadbalancer.server.port=8648
    depends_on:
      - seed2
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.4/tcp/8443/ws
      - NIMIQ_HOST=seed3.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ79VVKKSSCGHJUJKFHVEA1YNEJ66P7SST56
      - SIGNING_KEY=fb9313e42037e9acd6105c5a5e1264c5d8df917f9076f26f266051e121c5611b
      - VOTING_KEY=19182eb150e8eb273ba637383f68957e763ad50153e089a31775e1395844f5958a1bff3974e5f2860a14a9fda4d4560f4cafa28fc37e7253f21d12c102356db80ccee7d43852b6948d31b56336bcc95deea71ca0203ed5ab96f75736dba700
      - FEE_KEY=a436860a1efb3b70a11515720b6afa9a36de2531292183a966babc684a7e8f4e
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.4
    # volumes:
    #   - "seed3:/home/nimiq/.nimiq:rw"

  seed4:
    image: nimiq-albatross:latest
    build:
      context: albatross
      dockerfile: build_ubuntu.Dockerfile
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed4.rule=Host(`seed4.${NETWORK_NAME:?err}`)
      # Accept outside RPC connections
      - traefik.http.routers.seed4-rpc.rule=Host(`seed4.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed4-rpc.entrypoints=rpc
      - traefik.http.routers.seed4-rpc.service=seed4-rpc
      - traefik.http.services.seed4-rpc.loadbalancer.server.port=8648
    depends_on:
      - seed3
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.5/tcp/8443/ws
      - NIMIQ_HOST=seed4.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ83BPY4JPJH5B1YNYKQ32V184L4YU351VTL
      - SIGNING_KEY=973e58d73a7316673c9edf05397accac0123a8111240e1764119211f5a68b7e4
      - VOTING_KEY=d18cf85b0207c1531f72f3d6c1327ebef6d8cfd28fc7ceba33dc5e010ebcb45c99f2b906b3174cc452ecadc3978dc5a46ba6ce2290fc22eb8b303e4492c272d3893d39924906ebc057be749cfc64be3f19471699abb59a3f96503c89993300
      - FEE_KEY=f52865adebd028d36660b1150bde7f73ad8143ac58027023ceb528d57f49ec1c
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.5
    # volumes:
    #   - "seed4:/home/nimiq/.nimiq:rw"

volumes:
  seed1:
  seed2:
  seed3:
  seed4:
